insert into materia values (1, 'Taller Inicial Común: Taller de Lectura y Escritura');
insert into materia values (2, 'Taller Inicial Orientado: Ciencias Exactas');
insert into materia values (3, 'Taller Inicial Obligatorio del Área de Matemática');
insert into materia values (4, 'Introducción a la Programación');
insert into materia values (5, 'Taller de Lectura y Escritura en las Disciplinas');
insert into materia values (6, 'Introducción a la Matemática');
insert into materia values (7, 'Programación I');
insert into materia values (8, 'Organización del Computador');
insert into materia values (9, 'Inglés Lectocomprensión I');
insert into materia values (10, 'Programación II');
insert into materia values (11, 'Sistemas Operativos y Redes');
insert into materia values (12, 'Lógica y Teoría de Números');
insert into materia values (13, 'Programación III');
insert into materia values (14, 'Problemas Socioeconómicos Contemporáneos');
insert into materia values (15, 'Inglés Lectocomprensión II');
insert into materia values (16, 'Gestión y Administración de Bases de Datos');
insert into materia values (17, 'Matemática Discreta');
insert into materia values (18, 'Inglés Lectocomprensión III');
insert into materia values (19, 'Ingeniería de Software');
insert into materia values (20, 'Laboratorio de Construcción de Software');
insert into materia values (21, 'Especificación de Software');
